receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  tail_sampling:
    policies:
      - name: latency
        type: latency
        latency: {threshold_ms: 1000}
      - name: error-rate
        type: status_code
        status_code: {status_codes: [ERROR]}

exporters:
  otlphttp:
    endpoint: "http://jaeger:4318"
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]
